# MySQL Connection Settings
# Use the environment variable DB_URL if it exists; otherwise, use localhost for local dev
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/gym_management}

# Use DB_USER variable; default to root for local dev
spring.datasource.username=${DB_USER:root}

# Use DB_PASSWORD variable; default to empty for local dev
spring.datasource.password=${DB_PASSWORD:Tanisha@2005}

server.port=${PORT:8080}

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect