# H2 Database Settings (Works instantly on Render)
spring.datasource.url=jdbc:h2:mem:gymdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Tanisha@2005
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console (Optional: let's you see the DB at /h2-console)
spring.h2.console.enabled=true

# Keep your Server and Security settings
server.port=${PORT:8080}
spring.security.user.name=admin
spring.security.user.password=admin123

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true