# --- DATABASE (H2) ---
spring.datasource.url=jdbc:h2:mem:gymdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Tanisha@2005
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# --- SECURITY & SERVER ---
server.port=${PORT:8080}
spring.security.user.name=admin
spring.security.user.password=admin123